---
###############################
## Get Application ID       ###
###############################
    - name: Get App ID from Ravello
      ravello_get_app:
        application_name: "{{ ravello_app_name }}"
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
      register: app
      run_once: true
      tags:
        - fqdn

###############################
## Get VM ID       ###
###############################
    - name: Get VM ID from Ravello
      ravello_get_vm:
        application_id: "{{ app.json.id }}"
        vm_name: "{{ inventory_hostname }}"
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
      register: vm
      tags:
        - fqdn

###############################
##  Check VM Connectivity    ##
###############################
    - name: Get VM public FQDN
      uri:
        url: "https://cloud.ravellosystems.com/api/v1/applications/{{ app.json.id }}/vms/{{ vm.json.id }}/fqdn;deployment"
        method: GET
        user: "{{ ravello_login_username }}"
        password: "{{ ravello_login_password }}"
        force_basic_auth: yes
        status_code: 200
        HEADER_Content-Type: 'application/json'
        HEADER_Accept: 'application/json'
      register: ravello_public_ip
      tags:
        - fqdn

    # - debug: var=fqdn.json.value

    - name: Check ssh connectivity
      wait_for:
        host: "{{ ravello_public_ip.json.value }} "
        port: "{{ ravello_connectivity_port }}"
        timeout: "{{ ravello_connectivity_timeout }}"
      when: ravello_connectivity_check == true
      tags:
        - fqdn
