language: python
python:
  - 2.7

sudo: required
dist: trusty

env:
  - ANSIBLE_VERSION=2.2.0.0
  - ANSIBLE_VERSION=2.1.3.0

install:
  - docker build --build-arg ver_ansible=$ANSIBLE_VERSION -t juniper/ravello-ansible .

script:
  - make test
