---
- name: Delete Application on Ravello
  connection: local
  hosts: all
  gather_facts: no
  roles:
    - ravello.lib
    - ravello.application_delete
  pre_tasks:
    - include_vars: user-input.yaml
