---
- name: Get FQDN for all VM on Ravello
  connection: local
  hosts: all
  gather_facts: no
  roles:
    - ravello.lib
    - ravello.get_fqdn
  pre_tasks:
    - include_vars: user-input.yaml
  vars:
    ravello:
      connectivity_check: false
  tasks:
    - name: Delete previous file
      file:
        path: "host_vars/{{ inventory_hostname}}/fqdn.yaml"
        state: absent

    - name: Populate Junos Host Variable based on FQDN
      lineinfile:
        create: yes
        dest: "host_vars/{{ inventory_hostname}}/fqdn.yaml"
        line: "ansible_ssh_host: {{ ravello_public_ip.json.value }}"
