---
- name: Create Application on Ravello
  connection: local
  hosts: junos,server
  gather_facts: no
  serial: 1
  roles:
    - ravello.lib
    - ravello.application_create
  pre_tasks:
    - include_vars: user-input.yaml
